version: '3.5'
services:
  angular-staging:
    container_name: angular-staging
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - '.:/usr/src/app'
    ports:
    - '4200:4200'